### ISSUE TITLE
game in widecreen on 16:9 monitor

### ISSUE THREAD

**Issue by AriaHiro64** [mountnside/mupen64plus-video-parallel#3]
before the video was shrunk width wise but now its stretched

**Comment by mountnside** [comment]
yep, i know about this. I really should work on aspect moar. Did any previous commit work?

**Comment by mountnside** [comment]
![Capture](https://user-images.githubusercontent.com/78623397/112922834-e7615f80-9158-11eb-8d03-b2a9cf751f27.PNG)

**Comment by AriaHiro64** [comment]
![image](https://user-images.githubusercontent.com/45049787/112932675-52288180-90ec-11eb-9402-474227ce0e12.png)
windowed mode works but now full screen is weird. good progress tho

**Comment by mountnside** [comment]
hmmm is there a fullscreen resolution selector option in m64p?

**Comment by AriaHiro64** [comment]
not in m64p as its shipped with gliden64 and angrylion which do it automatically. i suppose i could put it in the ini

**Comment by mountnside** [comment]
I suppose I can set the fullscreen res automatically as a multiple of 640x480, as that is the base res that Parallel-RDP runs at.

**Comment by mountnside** [comment]
should be somewhat fixed now, seems so on my end, right now using the general "ScreenWidth" and "ScreenHeight" keys.

**Comment by mountnside** [comment]
Tested with m64p now.

This is really sick. 

Parallel-RDP now runs as a perfect replacement for angrylion-plus, just compile, drop in, and rename the DLL.

**Comment by AriaHiro64** [comment]
can confirm that the issue is solved
![image](https://user-images.githubusercontent.com/45049787/113080765-6c726600-91a5-11eb-81af-7db76c68ea04.png)
