### ISSUE TITLE
crashes when ending emulation in gui based frontends

### ISSUE THREAD

**Issue by AriaHiro64** [mountnside/mupen64plus-video-parallel#5]
not a huge issue but makes it annoying to swap games
spits out this error in mupen64plus-qt
[WARN]: Current NVIDIA driver is known to be slightly faster without 8/16-bit integer arithmetic.

**Comment by mountnside** [comment]
Tested, should be fixed now. Sorry for the hassles.

**Comment by AriaHiro64** [comment]
can confirm working
