### ISSUE TITLE
Jitter on screen between scene transitions on Star Fox 64 (USA)

### ISSUE THREAD

**Issue by Zet-sensei** [mountnside/mupen64plus-video-parallel#7]
Tested with M64p (Feb 23, 2021).
Replaced mupen64plus-video-angrylion-plus.dll by your version.
mupen64plus-video-parallel (commit 97a4627), compiled with MSYS64 on Win10.

![Jitter](https://user-images.githubusercontent.com/52127625/113288400-35a86700-92ef-11eb-8710-daeebf9e7e30.png)

**Comment by mountnside** [comment]
Seems to be a problem in the VK Mupen libretro core. Possible upstream problem in parallel-rdp?

**Comment by mountnside** [comment]
no response so....

**Comment by Zet-sensei** [comment]
I wasn't available yesterday, so I didn't had a chance to ask to TheMaister or m4xw until today.
